name: Python-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v4
      
      - name: Set up Python 
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 

      - name: Run flake8 
        run: flake8 .

      - name: Check for dependency vulnerabilities
        run: safety check -r requirements.txt

      - name: Run bandit
        run: bandit -r .


  publish:
    runs-on: ubuntu-latest
    needs:
       build
